/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/[_]gallery'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ArenaIndexRouteImport } from './routes/arena/index'
import { Route as ArenaReplayIdRouteImport } from './routes/arena/$replayId'
import { Route as BotsIdRouteImport } from './routes/bots/$id'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as EditorBotIdRouteImport } from './routes/editor/$botId'
import { Route as HillsIndexRouteImport } from './routes/hills/index'
import { Route as HillsSlugRouteImport } from './routes/hills/$slug'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments/$id'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as EmbedArenaIndexRouteImport } from './routes/embed/arena/index'
import { Route as EmbedArenaReplayIdRouteImport } from './routes/embed/arena/$replayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  path: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaReplayIdRoute = ArenaReplayIdRouteImport.update({
  id: '/arena/$replayId',
  path: '/arena/$replayId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIdRoute = BotsIdRouteImport.update({
  id: '/bots/$id',
  path: '/bots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorBotIdRoute = EditorBotIdRouteImport.update({
  id: '/editor/$botId',
  path: '/editor/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const HillsIndexRoute = HillsIndexRouteImport.update({
  id: '/hills/',
  path: '/hills/',
  getParentRoute: () => rootRouteImport,
} as any)
const HillsSlugRoute = HillsSlugRouteImport.update({
  id: '/hills/$slug',
  path: '/hills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedArenaIndexRoute = EmbedArenaIndexRouteImport.update({
  id: '/embed/arena/',
  path: '/embed/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedArenaReplayIdRoute = EmbedArenaReplayIdRouteImport.update({
  id: '/embed/arena/$replayId',
  path: '/embed/arena/$replayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_gallery': typeof GalleryRoute
  '/docs': typeof DocsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/arena/$replayId': typeof ArenaReplayIdRoute
  '/bots/$id': typeof BotsIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/editor/$botId': typeof EditorBotIdRoute
  '/hills/$slug': typeof HillsSlugRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/arena/': typeof ArenaIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/hills/': typeof HillsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/embed/arena/$replayId': typeof EmbedArenaReplayIdRoute
  '/embed/arena/': typeof EmbedArenaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/arena/$replayId': typeof ArenaReplayIdRoute
  '/bots/$id': typeof BotsIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/editor/$botId': typeof EditorBotIdRoute
  '/hills/$slug': typeof HillsSlugRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/arena': typeof ArenaIndexRoute
  '/docs': typeof DocsIndexRoute
  '/editor': typeof EditorIndexRoute
  '/hills': typeof HillsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/embed/arena/$replayId': typeof EmbedArenaReplayIdRoute
  '/embed/arena': typeof EmbedArenaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gallery': typeof GalleryRoute
  '/docs': typeof DocsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/arena/$replayId': typeof ArenaReplayIdRoute
  '/bots/$id': typeof BotsIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/editor/$botId': typeof EditorBotIdRoute
  '/hills/$slug': typeof HillsSlugRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/arena/': typeof ArenaIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/hills/': typeof HillsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/embed/arena/$replayId': typeof EmbedArenaReplayIdRoute
  '/embed/arena/': typeof EmbedArenaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_gallery'
    | '/docs'
    | '/settings'
    | '/stats'
    | '/arena/$replayId'
    | '/bots/$id'
    | '/docs/$'
    | '/editor/$botId'
    | '/hills/$slug'
    | '/tournaments/$id'
    | '/u/$handle'
    | '/arena/'
    | '/docs/'
    | '/editor/'
    | '/hills/'
    | '/tournaments/'
    | '/embed/arena/$replayId'
    | '/embed/arena/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_gallery'
    | '/settings'
    | '/stats'
    | '/arena/$replayId'
    | '/bots/$id'
    | '/docs/$'
    | '/editor/$botId'
    | '/hills/$slug'
    | '/tournaments/$id'
    | '/u/$handle'
    | '/arena'
    | '/docs'
    | '/editor'
    | '/hills'
    | '/tournaments'
    | '/embed/arena/$replayId'
    | '/embed/arena'
  id:
    | '__root__'
    | '/'
    | '/_gallery'
    | '/docs'
    | '/settings'
    | '/stats'
    | '/arena/$replayId'
    | '/bots/$id'
    | '/docs/$'
    | '/editor/$botId'
    | '/hills/$slug'
    | '/tournaments/$id'
    | '/u/$handle'
    | '/arena/'
    | '/docs/'
    | '/editor/'
    | '/hills/'
    | '/tournaments/'
    | '/embed/arena/$replayId'
    | '/embed/arena/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  DocsRoute: typeof DocsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  ArenaReplayIdRoute: typeof ArenaReplayIdRoute
  BotsIdRoute: typeof BotsIdRoute
  EditorBotIdRoute: typeof EditorBotIdRoute
  HillsSlugRoute: typeof HillsSlugRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  UHandleRoute: typeof UHandleRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  HillsIndexRoute: typeof HillsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  EmbedArenaReplayIdRoute: typeof EmbedArenaReplayIdRoute
  EmbedArenaIndexRoute: typeof EmbedArenaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery': {
      id: '/_gallery'
      path: '/_gallery'
      fullPath: '/_gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/': {
      id: '/arena/'
      path: '/arena'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$replayId': {
      id: '/arena/$replayId'
      path: '/arena/$replayId'
      fullPath: '/arena/$replayId'
      preLoaderRoute: typeof ArenaReplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$id': {
      id: '/bots/$id'
      path: '/bots/$id'
      fullPath: '/bots/$id'
      preLoaderRoute: typeof BotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$botId': {
      id: '/editor/$botId'
      path: '/editor/$botId'
      fullPath: '/editor/$botId'
      preLoaderRoute: typeof EditorBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hills/': {
      id: '/hills/'
      path: '/hills'
      fullPath: '/hills/'
      preLoaderRoute: typeof HillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hills/$slug': {
      id: '/hills/$slug'
      path: '/hills/$slug'
      fullPath: '/hills/$slug'
      preLoaderRoute: typeof HillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/arena/': {
      id: '/embed/arena/'
      path: '/embed/arena'
      fullPath: '/embed/arena/'
      preLoaderRoute: typeof EmbedArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/arena/$replayId': {
      id: '/embed/arena/$replayId'
      path: '/embed/arena/$replayId'
      fullPath: '/embed/arena/$replayId'
      preLoaderRoute: typeof EmbedArenaReplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  DocsRoute: DocsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  ArenaReplayIdRoute: ArenaReplayIdRoute,
  BotsIdRoute: BotsIdRoute,
  EditorBotIdRoute: EditorBotIdRoute,
  HillsSlugRoute: HillsSlugRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  UHandleRoute: UHandleRoute,
  ArenaIndexRoute: ArenaIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  HillsIndexRoute: HillsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  EmbedArenaReplayIdRoute: EmbedArenaReplayIdRoute,
  EmbedArenaIndexRoute: EmbedArenaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
