/**
 * `@asmbots/protocol`: what the web app, the API, and the CLI say to each other. Zod schemas and
 * their types for the API's records, replays, share links, `LiveRoom` messages, and errors. It
 * runs in the browser, the Worker, and Bun: no Node built-ins.
 */
export {
  AdminJob,
  AdminRoom,
  AdminStats,
  API_TOKEN,
  ApiToken,
  ApiTokenList,
  AssembleRequest,
  AssembleResult,
  AUDIT_ACTIONS,
  AuditAction,
  AuditEntry,
  AuditList,
  BotDetail,
  BotLabel,
  BotPlacement,
  BotVersionDetail,
  ChampionshipList,
  ChampionshipResult,
  CreatedApiToken,
  CreatedTournament,
  CreateTournament,
  Diagnostic,
  EarnedBadge,
  EnterTournament,
  HillBest,
  HillDetail,
  HillEventSummary,
  HillHistory,
  HillList,
  HillStanding,
  HillSubmitRequest,
  HillSubmitted,
  HillSummary,
  ImportBotsRequest,
  ImportBotsResult,
  ImportedBot,
  Leaderboard,
  LeaderRow,
  MAX_API_TOKENS,
  MAX_BOTS_PER_USER,
  MAX_IMPORT,
  MAX_SOURCE_TEXT,
  MAX_TOURNAMENT_ENTRANTS,
  MAX_VERIFIED_CYCLES,
  MAX_VERSIONS_PER_BOT,
  MatchList,
  MatchSummary,
  MatchVerification,
  Me,
  MyBot,
  MyBotList,
  NewApiToken,
  NewBot,
  NewBotVersion,
  ReplayUpload,
  RunnerReport,
  SavedBot,
  SavedBotVersion,
  SiteStats,
  STATS_TTL_SECONDS,
  StatsDay,
  StatsHill,
  StatsRecord,
  StoredReplay,
  SubmissionDetail,
  SubmissionProgress,
  TICKER_TTL_MS,
  Ticker,
  TickerChampionship,
  TickerHillEvent,
  TournamentDetail,
  TournamentEntered,
  TournamentEntrants,
  TournamentList,
  TournamentStarted,
  TournamentSummary,
  UpdateBot,
  UpdatedBot,
  UpdateMe,
  UserDay,
  UserDetail,
  UserStats,
} from './api'
export {
  awardBadges,
  BADGE_GROUPS,
  BADGE_IDS,
  BADGES,
  type Badge,
  type BadgeGroup,
  type BadgeId,
  badgeValue,
  type Earned,
  type MilestoneBadge,
  type PlayerFacts,
  type TitleBadge,
} from './badges'
export { fromBase64, fromBase64Url, sha256Hex, toBase64, toBase64Url } from './bytes'
export { canonicalJson } from './canonical'
export {
  EditorLayout,
  EditorLayoutList,
  EditorLayoutSaved,
  EditorLayoutTree,
  MAX_EDITOR_LAYOUT_BYTES,
  MAX_EDITOR_LAYOUTS,
  SaveEditorLayout,
  UpdateEditorLayout,
} from './editor-layouts'
export { ApiError, apiError, ERROR_STATUS, type ErrorCode } from './errors'
export { HillOverview, HillPulse, OVERVIEW_EVENTS } from './hill-overview'
export {
  HillJob,
  hillJobId,
  JOB_STATUSES,
  JobRef,
  JobStatus,
  RunnerJob,
  runnerJobId,
  TournamentJob,
} from './jobs'
export { entrantNames } from './labels'
export {
  Hello,
  LIVE_PING,
  LIVE_PONG,
  LIVE_PROTOCOL,
  LiveEvent,
  LiveMatch,
  LiveMessage,
  LiveRoomRef,
  liveRoomName,
  MatchFinished,
  MatchStarted,
  Ping,
  Pong,
  Progress,
  parseLiveMessage,
  parseLiveRoomName,
  Spectators,
  Standing,
  Standings,
} from './live'
export {
  Bot,
  BotVersion,
  DELETED_HANDLE,
  Handle,
  HILL_EVENT_KINDS,
  HILL_SEED,
  Hill,
  HillEntry,
  HillEvent,
  HillEventKind,
  HillScoring,
  HillSubmission,
  HOUSE_AUTHOR,
  HOUSE_HANDLE,
  handleProblem,
  isAllowedHandle,
  Match,
  MatchOutcome,
  RESERVED_HANDLES,
  SUBMISSION_STATUSES,
  SubmissionStatus,
  Tournament,
  TournamentConfig,
  TournamentEntry,
  TournamentKind,
  TournamentSeeding,
  TournamentStatus,
  User,
  Visibility,
} from './models'
export {
  BRAND,
  CARD_HEIGHT,
  CARD_WIDTH,
  headTags,
  PAGES_MANIFEST,
  type PageHead,
  type PageMeta,
  type PagesManifest,
  readPagesManifest,
  routeTitle,
  type SitemapEntry,
  sitemapUrls,
  sitemapXml,
} from './pages'
export {
  BotMetaSchema,
  type BuildReplayInput,
  buildReplay,
  bytesProblem,
  ISA,
  MAX_REPLAY_BOTS,
  MAX_REPLAY_CYCLES,
  MAX_REPLAY_ROUNDS,
  MIN_REPLAY_BOTS,
  matchResultHash,
  parseReplay,
  Replay,
  ReplayBot,
  ReplayConfig,
  type ReplayInputBot,
  ReplayResult,
  RoundResult,
  replayBots,
  replayConfig,
  replayKey,
  replayMatch,
  Seed,
  withoutSources,
} from './replay'
export { Id, ProtocolError, parse, SHA256, Slug } from './schema'
export {
  BotRef,
  decodeReplayFragment,
  decodeShare,
  decodeSources,
  encodeReplayFragment,
  encodeShare,
  encodeSources,
  MAX_REPLAY_FRAGMENT,
  MAX_SHARED_TEXT,
  REPLAY_KEY,
  SharedSource,
  ShareLink,
  SOURCES_KEY,
} from './share'
export {
  classOfRange,
  MAX_BOT_BYTES_ALL,
  MELEE_MAX_BOT_BYTES,
  OPEN_WEIGHT,
  WEIGHT_CLASSES,
  type WeightClass,
  type WeightClassSlug,
  weightClassOf,
} from './weight'
