// Generated by `bun run roster-images` (scripts/roster-images.ts) from the roster's sources.
// Do not edit: packages/bots/test/images.test.ts fails when this is not what they assemble to.

/** A roster bot's assembly: its metadata, and its machine code in base64. */
export interface RosterImageData {
  readonly name: string
  readonly author: string
  readonly strategy: string
  readonly version: string
  readonly bytes: string
}

/** Each roster bot's assembly, by slug. */
export const ROSTER_IMAGE_DATA: Readonly<Record<string, RosterImageData>> = {
  imp: {
    name: 'Imp',
    author: 'ASM Bots',
    strategy: 'Copy myself one word ahead, forever',
    version: '',
    bytes: '6AAAW4PrA413DY1/D6WQ',
  },
  'imp-ring': {
    name: 'Imp Ring',
    author: 'ASM Bots',
    strategy: 'Three imps a third of the core apart',
    version: '',
    bytes: '6AAAW4PrA413IrkCAIHGVlXHBKWQjXwCYsbi8Y13Io1/JKWQ',
  },
  dwarf: {
    name: 'Dwarf',
    author: 'ASM Bots',
    strategy: 'Bomb every 4th byte, walking backward',
    version: '',
    bytes: '6AAAW4PrA4nfufo/g+8ExwUAAOL36/A=',
  },
  'dwarf-wide': {
    name: 'Dwarf Wide',
    author: 'ASM Bots',
    strategy: 'Bomb every 3rd byte, four bombs a pass',
    version: '',
    bytes: '6AAAW4PrAzHAjX/9uVIViQWJRf2JRfqJRfeD7wzi8Ovo',
  },
  gate: {
    name: 'Gate',
    author: 'ASM Bots',
    strategy: 'Stop imps at the gate, bomb the core',
    version: '',
    bytes: '6AAAW4PrAzHAYBr/T/D/T/D/T/D/T/D/T/D/T/D/T/D/T/Dr5o1/97kaB4kFiUX3iUXuiUXlg+8k4vDr6A==',
  },
  decoy: {
    name: 'Decoy',
    author: 'ASM Bots',
    strategy: 'Hide in 2 KB of mov noise, then bomb',
    version: '',
    bytes: '6AAAW4PrA7ihAI2/APy5AALzq41/NbkAAvOrMcCNf/y5/A+JBYlF/IlF+IlF9IPvEOLw6+g=',
  },
  bastion: {
    name: 'Bastion',
    author: 'ASM Bots',
    strategy: 'An unrolled bomber between two fields of fake code',
    version: '',
    bytes:
      '60ChzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHM6AAAW4PrRTHAjX+Aja0A/7l+AIlFfIlFeIlFdIlFcIlFbIlFaIlFZIlFYIlFXIlFWIlFVIlFUIlFTIlFSIlFRIlFQIlFPIlFOIlFNIlFMIlFLIlFKIlFJIlFIIlFHIlFGIlFFIlFEIlFDIlFCIlFBIkFiUX8iUX4iUX0iUXwiUXsiUXoiUXkiUXgiUXciUXYiUXUiUXQiUXMiUXIiUXEiUXAiUW8iUW4iUW0iUWwiUWsiUWoiUWkiUWgiUWciUWYiUWUiUWQiUWMiUWIiUWEiUWAiUZ8iUZ4iUZ0iUZwiUZsiUZoiUZkiUZgiUZciUZYiUZUiUZQiUZMiUZIiUZEiUZAiUY8iUY4iUY0iUYwiUYsiUYoiUYkiUYgiUYciUYYiUYUiUYQiUYMiUYIiUYEiUYAiUb8iUb4iUb0iUbwiUbsiUboiUbkiUbgiUbciUbYiUbUiUbQiUbMiUbIiUbEiUbAiUa8iUa4iUa0iUawiUasiUaoiUakiUagiUaciUaYiUaUiUaQiUaMiUaIiUaEiUaAge8AAoHtAALiA+lq/ulx/qHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocyhzKHMocw=',
  },
  stone: {
    name: 'Stone',
    author: 'ASM Bots',
    strategy: 'Two bombers, two strides, one decoy imp',
    version: '',
    bytes:
      '6AAAW4PrAzHAjbcAQMcEpZCNfAJixmAYjX/8ufsPiQWJRfyJRfiJRfSD7xDi8OvojX/1uc8FiQWJRfWJReqJRd+D7yzi8Ovo',
  },
  paper: {
    name: 'Paper',
    author: 'ASM Bots',
    strategy: 'Copy myself all over the core and start every copy',
    version: '',
    bytes: '6AAAW4PrA4nahvKBwjQSid6J17kRAPOlYsLHhRoJAADr6Q==',
  },
  silk: {
    name: 'Silk',
    author: 'ASM Bots',
    strategy: 'Start each copy first, then write it',
    version: '',
    bytes: '6AAAW4PrA4nYhuCJxf2BxTQSx0YA6/5ixY13Ko1+KrkWAPOlx4UaCQAA6+I=',
  },
  twins: {
    name: 'Twins',
    author: 'ASM Bots',
    strategy: 'Paper whose copies take turns: a dense burst, then a wide one',
    version: '',
    bytes:
      '6AAAW4PrA4nahvKBwjQSid6J17kGAfOlgHX/AWLCjb0OBzHA9ocLAgF0A+nCAIlFfIlFeIlFdIlFcIlFbIlFaIlFZIlFYIlFXIlFWIlFVIlFUIlFTIlFSIlFRIlFQIlFPIlFOIlFNIlFMIlFLIlFKIlFJIlFIIlFHIlFGIlFFIlFEIlFDIlFCIlFBIkFiUX8iUX4iUX0iUXwiUXsiUXoiUXkiUXgiUXciUXYiUXUiUXQiUXMiUXIiUXEiUXAiUW8iUW4iUW0iUWwiUWsiUWoiUWkiUWgiUWciUWYiUWUiUWQiUWMiUWIiUWEiUWA6Rv/iYVwBImFUASJhTAEiYUQBImF8AOJhdADiYWwA4mFkAOJhXADiYVQA4mFMAOJhRADiYXwAomF0AKJhbACiYWQAomFcAKJhVACiYUwAomFEAKJhfABiYXQAYmFsAGJhZABiYVwAYmFUAGJhTABiYUQAYmF8ACJhdAAiYWwAImFkACJRXCJRVCJRTCJRRCJRfCJRdCJRbCJRZCJhXD/iYVQ/4mFMP+JhRD/iYXw/omF0P6JhbD+iYWQ/omFcP6JhVD+iYUw/omFEP6JhfD9iYXQ/YmFsP2JhZD9iYVw/YmFUP2JhTD9iYUQ/YmF8PyJhdD8iYWw/ImFkPyJhXD8iYVQ/ImFMPyJhRD8iYXw+4mF0PuJhbD7iYWQ++kA/gA=',
  },
  scanner: {
    name: 'Scanner',
    author: 'ASM Bots',
    strategy: 'Scan down for code, carpet-bomb what I find',
    version: '',
    bytes: '6AAAW4PrAzHA/Y1/6rn///OujVUWKdqD+kxzBY1/6uvsg8cTuRAA86vr4g==',
  },
  hybrid: {
    name: 'Hybrid',
    author: 'ASM Bots',
    strategy: 'Scan and carpet-bomb; turn to paper when bombs land near home',
    version: '',
    bytes:
      '6AAAW4PrA7j//42/bQO5CADzqzHA/Y1/6LmAAPOudBiNVRgp2oH6tANzBY1/6Ovpg8cVuRAA86uJ/Y2/fAO5EADyrnQEie/r0OgAAFuD60z8idqG8oHCNBKNd0mJ17kSAPOlYsLHhRoJAADr6A==',
  },
  vampire: {
    name: 'Vampire',
    author: 'ASM Bots',
    strategy: 'Bite code with jmp fangs, hold the bitten in a pit',
    version: '',
    bytes:
      '6AAAW4PrAzHA/Y1/wIsVC1XwC1XgC1XQdQWD70Dr7oPHArkgAPOvjVVCKdqB+sMAcwqNf8DHR1kAAOvRg8cTjVdUKfq5EADGBemJVQGDwgOD7wPi8uu2MfZg/scAAACDxgKD5j/r8g==',
  },
  'painter-lcg': {
    name: 'LCG Painter',
    author: 'ASM Bots',
    strategy: 'Scatter 0xAA in drifting clouds that jump now and then',
    version: '',
    bytes: '6AAAW4PrA75tTonYjW839+YFOTCD1QCJ14HnHx/GA6qE0nXricWNfzYp74H/JiBz3oHFAIDr2A==',
  },
  'painter-spiral': {
    name: 'Spiral Painter',
    author: 'ASM Bots',
    strategy: 'Paint 0x55 in a square spiral around myself',
    version: '',
    bytes: '6AAAW4PrAzH/vgEAvQABugEAidEB94P/LXIDxgFV4vSH7vfdQoH6/wBy5+va',
  },
  halt: {
    name: 'Halt',
    author: 'ASM Bots',
    strategy: 'Run hlt at once and die',
    version: '',
    bytes: '9A==',
  },
  spin: {
    name: 'Spin',
    author: 'ASM Bots',
    strategy: 'Jump to itself forever',
    version: '',
    bytes: '6/4=',
  },
  count: {
    name: 'Count',
    author: 'ASM Bots',
    strategy: 'Count ax up to 100, then spin',
    version: '',
    bytes: 'QIP4ZHL66/4=',
  },
  'spl-storm': {
    name: 'SPL Storm',
    author: 'ASM Bots',
    strategy: 'Split until the process cap, and keep trying',
    version: '',
    bytes: 'YP7r/A==',
  },
  'stack-walk': {
    name: 'Stack Walk',
    author: 'ASM Bots',
    strategy: 'Push 256 words below myself, then spin',
    version: '',
    bytes: 'uQABUeL96/4=',
  },
  'rep-copy': {
    name: 'Rep Copy',
    author: 'ASM Bots',
    strategy: 'Copy 512 bytes with one rep movsw, then spin',
    version: '',
    bytes: '6AAAW4PrA4nejb8AELkAAfzzpev+',
  },
  'div-zero': {
    name: 'Div Zero',
    author: 'ASM Bots',
    strategy: 'Divide by zero and die',
    version: '',
    bytes: 'Mcn38ev+',
  },
  misalign: {
    name: 'Misalign',
    author: 'ASM Bots',
    strategy: 'Jump into the middle of my own instructions',
    version: '',
    bytes: 'YAbrAbhA1rjr/g==',
  },
}
