/**
 * `bun run roster-images` writes packages/bots/src/images.gen.ts: what each roster bot assembles
 * to (its `%name`, `%author`, `%strategy`, `%version`, and machine code in base64), so a page can
 * fight the roster with neither the assembler nor the sources (`rosterImage`). The bots past
 * lightweight go to images-large.gen.ts, which loads on demand (`large.ts`). Run it after a
 * change to a roster file, the assembler, or the codec. `--check` writes nothing and exits 1 when
 * a file is not what it would write; `scripts/roster-images.test.ts` runs that check in
 * `bun test`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRoster, ROSTER } from '../packages/bots/src/index'
import { WEIGHT_CLASSES } from '../packages/protocol/src/weight'

/** The generated modules: the lightweight bots, and the bots past lightweight. */
export const IMAGE_FILES = {
  light: fileURLToPath(new URL('../packages/bots/src/images.gen.ts', import.meta.url)),
  large: fileURLToPath(new URL('../packages/bots/src/images-large.gen.ts', import.meta.url)),
} as const

/** Which module a bot's image goes to. */
export type ImagePart = keyof typeof IMAGE_FILES

/** The largest bot `images.gen.ts` takes: the top of lightweight. */
export const LIGHT_MAX_BYTES = WEIGHT_CLASSES[0].max

/** Biome's line width (biome.json). */
const LINE_WIDTH = 100

/**
 * A string literal as Biome writes it: single quotes, unless the text has more single quotes than
 * double ones.
 */
export function literal(text: string): string {
  const singles = text.split("'").length - 1
  const doubles = text.split('"').length - 1
  const quote = singles > doubles ? '"' : "'"
  const escaped = text.replace(/\\/g, '\\\\').split(quote).join(`\\${quote}`)
  return `${quote}${escaped}${quote}`
}

/** An object key as Biome writes it: bare when it is an identifier. */
const key = (slug: string) => (/^[A-Za-z_$][\w$]*$/.test(slug) ? slug : literal(slug))

/** The roster bots whose images go to `part`'s module, in roster order. */
export function imageSlugs(part: ImagePart): string[] {
  const roster = loadRoster()
  return ROSTER.filter(({ slug }) => {
    const large = (roster.get(slug)?.assembled.bytes.length ?? 0) > LIGHT_MAX_BYTES
    return part === 'large' ? large : !large
  }).map(({ slug }) => slug)
}

/** The text of `part`'s module for the roster as it assembles now. */
export function imagesModule(part: ImagePart): string {
  const roster = loadRoster()
  const rows = imageSlugs(part).map((slug) => {
    const bot = roster.get(slug)
    if (bot === undefined) throw new Error(`loadRoster has no bot '${slug}'`)
    const { name, author, strategy, version, bytes, diagnostics } = bot.assembled
    if (diagnostics.some((d) => d.severity === 'error')) {
      throw new Error(`roster bot '${slug}' does not assemble`)
    }
    const fields = Object.entries({
      name,
      author,
      strategy,
      version,
      bytes: Buffer.from(bytes).toString('base64'),
    }).map(([field, value]) => {
      const line = `    ${field}: ${literal(value)},`
      // Past the line width, Biome puts the value on a line of its own.
      return line.length <= LINE_WIDTH ? line : `    ${field}:\n      ${literal(value)},`
    })
    return `  ${key(slug)}: {\n${fields.join('\n')}\n  },`
  })
  if (part === 'large') {
    return `// Generated by \`bun run roster-images\` (scripts/roster-images.ts) from the roster's sources.
// Do not edit: packages/bots/test/images.test.ts fails when this is not what they assemble to.
import type { RosterImageData } from './images.gen'

/** Each roster bot's assembly past lightweight (over ${LIGHT_MAX_BYTES} bytes), by slug. */
export const LARGE_IMAGE_DATA: Readonly<Record<string, RosterImageData>> = {
${rows.join('\n')}
}
`
  }
  return `// Generated by \`bun run roster-images\` (scripts/roster-images.ts) from the roster's sources.
// Do not edit: packages/bots/test/images.test.ts fails when this is not what they assemble to.

/** A roster bot's assembly: its metadata, and its machine code in base64. */
export interface RosterImageData {
  readonly name: string
  readonly author: string
  readonly strategy: string
  readonly version: string
  readonly bytes: string
}

/** Each lightweight roster bot's assembly, by slug; the others are in images-large.gen.ts. */
export const ROSTER_IMAGE_DATA: Readonly<Record<string, RosterImageData>> = {
${rows.join('\n')}
}
`
}

/**
 * Writes the modules to `files`, or with `check` compares `files` with them. Returns the exit
 * code: 1 when a file is stale.
 */
export function rosterImages(
  check: boolean,
  log: (line: string) => void = console.log,
  files: Readonly<Record<ImagePart, string>> = IMAGE_FILES,
): number {
  let code = 0
  for (const part of ['light', 'large'] as const) {
    const file = files[part]
    const text = imagesModule(part)
    const path = relative(process.cwd(), file)
    if (!check) {
      writeFileSync(file, text)
      log(`wrote ${path}: ${imageSlugs(part).length} bots`)
    } else if (readFileSync(file, 'utf8') === text) {
      log(`${path} is up to date`)
    } else {
      log(`${path} is stale: run \`bun run roster-images\``)
      code = 1
    }
  }
  return code
}

if (import.meta.main) {
  const args = process.argv.slice(2)
  if (args.some((a) => a !== '--check')) {
    console.error('usage: bun run roster-images [--check]')
    process.exit(2)
  }
  process.exit(rosterImages(args.includes('--check')))
}
